- name: Demonstrates use of our brand new custom add module
  hosts: all
  tasks:
   - name: Invoke the add custome module
     add: firstInput=100 secondInput=Soham
     register: output

   - name: Print the result
     debug: var=output
