- name: Configure nginx Web server on Ubuntu Containers
  copy: src=default dest=/etc/nginx/sites-available/default backup=yes
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
  notify:
      - Restart nginx web server

- name: Configure nginx Web server on CentOS containers
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
  notify:
   - Restart nginx web server
